services:
  sonarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /srv/ssd1/config/sonarr:/config
      - /srv/ssd1/SSD1/Continuing:/continuing
      - /srv/ssd1/SSD1/Downloads:/downloads
      - /srv/ssd1/SSD1/Series:/series
      - /srv/ssd1/SSD1/Anime:/anime2
      - /srv/ssd2/SSD2/Series:/series2
      - /srv/ssd2/SSD2/Continuing:/continuing2
      - /srv/ssd2/SSD2/Anime:/anime
    ports:
      - 8989:8989
    restart: unless-stopped
