---
version: "3"
services:
  sonarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /srv/ssd1/config/sonarr:/config
      - /srv/ssd1/WD/Continuing:/continuing
      - /srv/ssd1/WD/Downloads:/downloads
      - /srv/ssd1/WD/Series:/series
      - /srv/ssd1/WD/Anime:/anime
      - /srv/ssd2/WD/Series:/series2
      - /srv/ssd2/WD/Continuing:/continuing2
      - /srv/ssd2/WD/Anime:/anime2
    ports:
      - 8989:8989
    restart: unless-stopped
