---
version: "3"
services:
  sonarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /srv/my-mount/config/sonarr:/config
      - /srv/my-mount/WD/_New:/media
      - /srv/my-mount/WD/_Downloads:/downloads
      - /srv/my-mount/WD/Series:/series
    ports:
      - 8989:8989
    restart: unless-stopped
