version: "3"
services:
  qbittorrent:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - WEBUI_PORT=8080
    volumes:
      - /srv/my-mount/config/qbittorrent:/config
      - /srv/my-mount/WD/_Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
