version: "3"
services:
  overseerr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /srv/ssd1/config/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
