version: '3.3'
services:
  plex:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-jT_t4A18PZGW8rrKwbmQ
    volumes:
      - /srv/ssd1/config/plex:/config
      - /srv/ssd1/WD/Series:/tv
      - /srv/ssd1/WD/Movies:/movies
      - /srv/ssd1/WD/Continuing:/continuing
      - /srv/ssd1/WD/Anime:/anime
      - /srv/ssd2/WD/Series:/tv2
      - /srv/ssd2/WD/Movies:/movies2
      - /srv/ssd2/WD/Continuing:/continuing2
      - /srv/ssd2/WD/Anime:/anime2
    restart: unless-stopped
