version: '3.3'
services:
  plex:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-jT_t4A18PZGW8rrKwbmQ
    volumes:
      - /srv/my-mount/config/plex:/config
      - /srv/my-mount/WD/Series:/tv
      - /srv/my-mount/WD/Movies:/movies
      - /srv/my-mount/WD/_New:/new
    restart: unless-stopped
