---
version: "3"
services:
  radarr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - /srv/ssd1/config/radarr:/config
      - /srv/ssd1/WD/Downloads:/downloads
      - /srv/ssd1/WD/Movies:/movies
      - /srv/ssd2/WD/Movies:/movies2
    ports:
      - 7878:7878
    restart: unless-stopped
