services:
  jackett:
    container_name: jackett
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/jackett:latest
    mem_limit: 1024m
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - AUTO_UPDATE=true
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - "9117:9117"

volumes:
  jackett-config:
  jackett-downloads:
