version: '3.3'
services:
  jellyfin:
    labels:
        - com.centurylinklabs.watchtower.enable=true
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /srv/ssd1/config/jellyfin:/config
      - /srv/ssd1/WD/Series:/data/tvshows
      - /srv/ssd1/WD/_New:/data/new
      - /srv/ssd1/WD/Movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
