services:
  flaresolverr:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Africa/Nairobi
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 
