version: '3'

services:
  dash:
    labels:
      - com.centurylinklabs.watchtower.enable=true
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
